In [1]:
import pandas as pd
import numpy as np

In [2]:
train_data = pd.read_csv('datasets\kaggle_startups_train_28062024.csv')
display(train_data.head(10))

,name,category_list,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,first_funding_at,last_funding_at,closed_at
0,Lunchgate,Online Reservations|Restaurants,828626.0,operating,CHE,25,Zurich,Zürich,2,2009-10-17,2011-05-01,2014-12-01,NaN
1,EarLens,Manufacturing|Medical|Medical Devices,42935019.0,operating,USA,CA,SF Bay Area,Redwood City,4,2005-01-01,2010-05-04,2014-02-25,NaN
2,Reviva Pharmaceuticals,Biotechnology,35456381.0,operating,USA,CA,SF Bay Area,San Jose,3,2006-01-01,2012-08-20,2014-07-02,NaN
3,Sancilio and Company,Health Care,22250000.0,operating,NaN,NaN,NaN,NaN,3,2004-01-01,2011-09-01,2014-07-18,NaN
4,WireTough Cylinders,Manufacturing,NaN,operating,USA,VA,VA - Other,Bristol,1,2010-05-12,2012-02-01,2012-02-01,NaN
5,Connected Sports Ventures,Mobile,4300000.0,operating,USA,NJ,Newark,Princeton,1,2011-04-16,2012-11-12,2012-11-12,NaN
6,Attensity,Analytics|Business Analytics|Social CRM|Social...,90000000.0,operating,USA,CA,SF Bay Area,Redwood City,1,2000-01-01,2014-05-14,2014-05-14,NaN
7,Mesh Networks,Software,4300000.0,operating,USA,TX,Houston,Houston,1,2005-01-01,2014-11-09,2014-11-09,NaN
8,AngioScore,Biotechnology,42000000.0,operating,USA,CA,SF Bay Area,Fremont,2,2003-01-01,2007-10-09,2011-04-20,NaN
9,Vidatronic,Semiconductors,1250500.0,operating,USA,TX,Austin,College Station,2,2010-01-01,2011-08-23,2013-03-21,NaN

import pandas as pd

def encode_text_values(df, feature):

    # Подсчитываем частоту каждого уникального значения
    value_counts = df[feature].value_counts()

    # Определяем границу отсечения
    top = value_counts.nlargest(2).index

    # Создаем словарь для кодирования
    encoding_dict = {value: i+1 for i, value in enumerate(top)}

    # Функция для кодирования значения
    def encode(value):
        return encoding_dict.get(value, 0)

    # Применяем функцию кодирования к каждому значению
    df[feature] = df[feature].apply(encode)

    return df

In [3]:
value_counts = train_data['category_list'].value_counts()
value_counts

category_list
Software                                                                                  3207
Biotechnology                                                                             2905
E-Commerce                                                                                1064
Mobile                                                                                     920
Clean Technology                                                                           892
                                                                                          ...
iPad|Reviews and Recommendations|Social Television|Software|Television|Video on Demand       1
Graphics|Software|Startups                                                                   1
Curated Web|File Sharing|Graphics|PaaS                                                       1
Cloud Computing|Cloud Data Services|Databases|IaaS|Services|Software|Virtualization          1
Online Rental|Parking|Price Comparison                                                       1
Name: count, Length: 22105, dtype: int64

In [4]:
top = value_counts.nlargest(2).index
top

Index(['Software', 'Biotechnology'], dtype='object', name='category_list')

In [11]:
encoding_dict = {value: i+1 for i, value in enumerate(top)}
encoding_dict

{'Software': 1, 'Biotechnology': 2}

In [14]:
encoding_dict.get('Software', 0)

1